services:
  frontend:
    build: frontend
    depends_on:
      - backend
    tty: true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend/
        - action: rebuild
          path: ./frontend/package.json
    environment:
      VITE_BACKEND_ORIGIN: "http://localhost:3001"
      PORT: 3000
    ports:
      - "3000:3000"

  backend:
    build: backend
    depends_on:
      - database
      - redis
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /backend/src/
        - action: sync+restart
          path: ./backend/index.js
          target: /backend/index.js
        - action: rebuild
          path: ./backend/package.json
    ports:
      - "3001:3001"
    volumes:
      - ./backend/logs:/backend/logs 
    environment:
      DOMAIN: "localhost"
      PORT: 3001
      FRONTEND_ORIGIN: "http://localhost:3000"
      COOKIE_SECRET: "s3cr3t"
      MONGO_URI: "mongodb://root:1234@database:27017"
      REDIS_URI: "redis://default:1234@redis:6379"
      COMPOSE_FILE_WATCHER_DEBUG: "1"

  database:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass "1234" --save 60 1 --loglevel warning