name: Test Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install root dependencies
        run: npm ci
      
      - name: Install backend dependencies
        run: cd backend && npm ci
        
      - name: Install frontend dependencies
        run: cd frontend && npm ci
        
      - name: Install test dependencies
        run: cd test && npm ci
        
      - name: Start Docker Compose services
        run: |
          docker-compose up -d
          # Wait for services to be ready
          sleep 20
          
      - name: Install Playwright browsers
        run: cd test && npx playwright install --with-deps
        
      - name: Run Playwright tests
        run: cd test && npx playwright test
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test/playwright-report/
          retention-days: 30
          
      - name: Stop Docker Compose services
        if: always()
        run: docker-compose down