name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install Root Dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: test
      run: npx playwright install --with-deps
    
    - name: Start Backend
      working-directory: backend
      run: |
        npm run build &
        npm start &
        sleep 10
    
    - name: Start Frontend
      working-directory: frontend
      run: |
        npm run build &
        npm start &
        sleep 10
    
    - name: Run Playwright tests
      working-directory: test
      run: npx playwright test
      env:
        FRONTEND_URL: http://localhost:3000
        BACKEND_URL: http://localhost:3001
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test/playwright-report/
        retention-days: 30
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-artifacts
        path: |
          test/test-results/
          test/playwright-report/
        retention-days: 5